### ISSUE TITLE
Logo des guildes

### ISSUE THREAD

**Issue by AudreySerna** [Crocmagnon/Rearth_PoleRecherche#10]
Les logos des guildes n'apparaissent pas (première lettre de la guilde encadrée à la place). J'ai vérifié, ils se trouvent dans `/app/assets/logos/`

**Comment by Crocmagnon** [comment]
Les logos ne me sont pas fournis par l'API Moodle, je n'ai pas l'impression de pouvoir les ajouter moi-même. Je vais tenter un fix.

**Comment by Crocmagnon** [comment]
Si les logos ne sont pas fournis, ils sont "déduits" à partir du nom de la guilde en minuscules et du nom de fichier actuel des logos.

**Comment by AudreySerna** [comment]
Ne pas mettre de logo quand guilde = aucun
