### ISSUE TITLE
Obtention de brevet paramétrable

### ISSUE THREAD

**Issue by AudreySerna** [Crocmagnon/Rearth_PoleRecherche#11]
Ce n'était pas dans les specifs, mais est-ce qu'il serait possible de rendre le nombre de technos découvertes au sein d'une guilde paramétrable (dans un json par exemple) pour l'obtention du brevet?

- pour l'instant il faut que 3 personnes de la guilde aient découvert la techno pour qu'ils obtiennent le brevet. Il faudrait pouvoir facilement (pour les enseignants) changer à 2 ou à 4 par exemple (je me dis que selon le nombre d'élèves dans la classe ça peut être utile).

Est-ce que ça demanderait beaucoup de travail?

**Comment by Crocmagnon** [comment]
C'est une variable à changer dans le code : https://github.com/Crocmagnon/Rearth_PoleRecherche/blob/4aafb46cc2fc5b5c9e81808ff08bec753d1faee3/app/core/requests-utils.js#L14

**Comment by AudreySerna** [comment]
Est-ce que l'on peut l'externaliser dans le JSON ou se trouvent les couts de pose de chaque infrastructure?

**Comment by Crocmagnon** [comment]
Pas idéal, il faudrait charger le json à chaque chargement du module.

**Comment by AudreySerna** [comment]
Regarder ou déplacer la variable

**Comment by Crocmagnon** [comment]
J'ai regardé, ça me semble assez illogique de placer cette variable ailleurs : ce n'est pas une simple donnée de jeu comme un coût mais bien une variable liée aux mécaniques du jeu.

Je propose qu'on la laisse ici mais qu'on soit clairs avec les enseignants pour qu'ils sachent quoi modifier si nécessaire. Cela vous convient-il ?

**Comment by AudreySerna** [comment]
OK
