### ISSUE TITLE
Corriger l'affichage de la guilde en possession d'un brevet

### ISSUE THREAD

**Issue by Crocmagnon** [Crocmagnon/Rearth_PoleRecherche#5]
Actuellement si une guilde possède un brevet, l'écran affiche "Guilde : a aucun".

**Comment by Crocmagnon** [comment]
La guilde "aucun" correspond à un brevet déposé par des utilisateurs "fantômes" (ne correspondant pas aux utilisateurs indiqués dans le fichier `licence_fichier_joueurs.ods`

**Comment by AudreySerna** [comment]
Je suis allée dans Niveau 2 de habitation et dans les progressions je n'ai vu aucune guilde qui a obtenu des brevets.

**Comment by Crocmagnon** [comment]
J'ai bien l'affichage de mon côté sur la version de test, voir la copie d'écran suivante : 

![screenshot](https://www.dropbox.com/s/irrf9dj0iaogm1w/Capture%20d%27%C3%A9cran%202017-11-20%2014.49.18.png?raw=1)

**Comment by AudreySerna** [comment]
AH oui OK pour ça. 
Mais en fait je parlais des barres de progression (avant qu'un brevet soit posé par une guilde).
Je viens de me rendre compte qu'il y a un chiffre affiché dans la barre de progression mais il ne se voit pas bien (j'ai passé ma souris dessus pour le voir sur la copie d'écran) :

![capture d ecran 2017-11-21 a 09 49 55](https://user-images.githubusercontent.com/19959737/33062997-5bec6936-cea1-11e7-8398-c35084db495e.png)

Dans les spécifs d'Estelle, on devait plutôt avoir des barres de progression qui se remplissent:

![capture d ecran 2017-11-21 a 09 51 52](https://user-images.githubusercontent.com/19959737/33063068-a711d72a-cea1-11e7-9706-a45d02d0ae57.png)

Est-ce qu'il est possible de le modifier sans trop de mal? (garder le 1/3 dans la barre serait encore mieux pour la clarté d'information).

**Comment by AudreySerna** [comment]
En parcourant l'appli, je vois que ça marche 
![capture d ecran 2017-11-21 a 10 04 44](https://user-images.githubusercontent.com/19959737/33063698-8190e516-cea3-11e7-8168-1277cf0aa243.png)

Du coup, il suffit de changer la couleur de texte pour que l'on voit les infos même quand la barre de progression est à 0.
Et peut-être centrer le texte à l'intérieur de la barre de progression

**Comment by Crocmagnon** [comment]
Fait : il y a toujours un petit peu de couleur en fond pour que le texte soit visible. Le texte reste centré sur la partie "remplie" de la barre
