### ISSUE TITLE
Ajouter un bouton refresh

### ISSUE THREAD

**Issue by Crocmagnon** [Crocmagnon/Rearth_PoleRecherche#7]
Ajouter un bouton pour rafraîchir les données du serveur Moodle

**Comment by AudreySerna** [comment]
Je n'ai pas testé mais ça me fait penser qu'il me faudrait la structure de données (ou les champs de la BD) qu'utilise ce refresh pour m'assurer que l'équipe de développement du jeu UNITY fasse bien les bonnes sauvegardes dans la BD moodle.

**Comment by Crocmagnon** [comment]
J'ai simplement utilisé la note "population". Il y a déjà une note "energie", j'en ai rajouté une pour chaque joueur du fichier que vous m'avez donné.
