### ISSUE TITLE
Achat brevet

### ISSUE THREAD

**Issue by AudreySerna** [Crocmagnon/Rearth_PoleRecherche#8]
Est-ce que l'achat de brevet fonctionne? Je n'ai pas pu tester vu qu'aucun brevet n'a été déposé.

**Comment by AudreySerna** [comment]
Je me rends compte que l'on n'a pas respecter le gameplay avec Estelle lorsqu'elle a implémentée les écrans:

Si un brevet est déposé par une guilde, tous les joueurs n’ayant pas encore découvert la technologie auront la possibilité d’acheter une licence d’utilisation de ce brevet. **Son prix sera très attractif pour les membres de la guilde titulaire du brevet, et sera au contraire très élevé pour tous les autres joueurs.** Pour qu’un brevet soit déposé par une guilde, au moins 3 de ses membres doivent avoir découvert la technologie concernée. Seuls ces 3 membres percevront les annuités payées à chaque tour par chacun des joueurs ayant acheté une licence de ce brevet.

**Comment by AudreySerna** [comment]
A moins que ça soit prévu lorsque l'on peut acheter un brevet?

**Comment by AudreySerna** [comment]
Dans  "Rearth_PoleRecherche/app/assets/context.json" c'est prévu (dans type de coût : "id": 6, "nom": "achat-lic-guilde").
Est-ce que c'est géré dans le code?

**Comment by Crocmagnon** [comment]
Le brevet est déposé automatiquement à lorsque le troisième membre de guilde découvre la technologie.

J'ai testé sur la technologie Habitation niveau 2, brevet déposé par les Energéticiens :
- Lorsqu'un Énergéticien veut acheter la licence, il doit payer 100 énergie et cela lui coûte 10 pop/tour.
- Lorsqu'un non énergéticien veut acheter la licence, il doit payer **150** énergie, 10 pop/tour.

Il semblerait donc que les deux types de prix soient gérés.
