### ISSUE TITLE
Validation exercice manuelle

### ISSUE THREAD

**Issue by AudreySerna** [Crocmagnon/Rearth_PoleRecherche#9]
Lorsque l'on entre le code rearth2016 pour la validation d'un exercice, rien ne se passe après avoir appuyer sur le bouton valider.

**Comment by Crocmagnon** [comment]
Si c'est un exercice non défini j'ai eu le souci aussi, mais pas de problème sur un exercice "défini" de mon côté.

**Comment by AudreySerna** [comment]
Est-ce que l'on ne peut pas faire un comportement par défaut pour les exercices papier (on pourrait avoir un type "exercice papier" à la place de "exercice non défini") pour que le bouton validation fonctionne?
Ca permettrait aux enseignants de proposer des exercices (même s'ils n'ont pas été prévus sur la tablette) et les valider dans l'application.

**Comment by Crocmagnon** [comment]
C'est une bonne idée, je regarde

**Comment by AudreySerna** [comment]
Vérifier la mise à jour
